
hostname: "localhost"

motd: |
  Hello y'all welcome to localhost.irc
  This is the MOTD.
  glhf.


listeners:
  tls:
    address: 127.0.0.1:6697
    tls: true
    tls_cert: "cert.pem"
    tls_key: "key.pem"
  plain:
    address: 127.0.0.1:6667
